"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../../lib/supabase";

type Order = { id: string; status: string; created_at: string; created_by: string | null; location: { name: string } | { name: string }[] | null; creator: { email: string } | { email: string }[] | null; order_items: { cartons: number; wine: { name: string }[] }[] };

function one<T>(value: T | T[] | null) { return Array.isArray(value) ? value[0] : value; }

export default function AdminOrdersPage() {
  const router = useRouter();
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  const [view, setView] = useState<"open" | "history">("open");
  const [notice, setNotice] = useState("");
  const loadOrders = async () => { const result = await supabase.from("orders").select("id,status,created_at,created_by,location:locations(name),creator:profiles!orders_created_by_fkey(email),order_items(cartons,wine:wines(name))").order("created_at", { ascending: false }); if (result.error) setNotice(result.error.message); else setOrders((result.data ?? []) as Order[]); setLoading(false); };
  useEffect(() => { let mounted = true; supabase.auth.getUser().then(async ({ data: { user } }) => { if (!user) { router.push("/"); return; } const profile = await supabase.from("profiles").select("role").eq("id", user.id).single(); if (profile.data?.role !== "super_admin") { setNotice("Nur der Super-Admin darf alle Bestellungen sehen."); setLoading(false); return; } if (mounted) await loadOrders(); }); return () => { mounted = false; }; }, [router]);
  const visibleOrders = useMemo(() => orders.filter((order) => view === "open" ? order.status === "submitted" : order.status === "delivered"), [orders, view]);
  async function completeOrder(id: string) { const { error } = await supabase.rpc("complete_order", { p_order_id: id }); if (error) { setNotice(error.message); return; } setOrders((items) => items.map((order) => order.id === id ? { ...order, status: "delivered" } : order)); setNotice("Bestellung als erledigt markiert und Bestand aktualisiert"); window.setTimeout(() => setNotice(""), 3500); }
  async function signOut() { await supabase.auth.signOut(); router.push("/"); }
  if (loading) return <main className="auth-page"><div className="auth-card"><div className="brand-mark">VB</div><h1>Bestellungen werden geladen …</h1></div></main>;
  if (notice && orders.length === 0) return <main className="auth-page"><div className="auth-card"><div className="brand-mark">VB</div><h1>Zugriff verweigert</h1><p>{notice}</p><button className="primary-button auth-submit" onClick={signOut}>Abmelden</button></div></main>;
  return <main className="inventory-page"><header className="inventory-top"><button className="back-button" onClick={() => router.push("/")}>← Dashboard</button><div className="top-actions"><button className="secondary-button" onClick={signOut}>Abmelden</button></div></header><div className="inventory-content"><div className="page-heading"><div><div className="eyebrow">Betriebsbestellungen · Geschützter Bereich</div><h1>Bestellungen</h1><p>Offene Bestellungen bearbeiten und erledigte Bestellungen nachsehen.</p></div></div>{notice && <div className="toast">✓ {notice}</div>}<div className="business-tabs"><button className={view === "open" ? "active" : ""} onClick={() => setView("open")}>Offen ({orders.filter((order) => order.status === "submitted").length})</button><button className={view === "history" ? "active" : ""} onClick={() => setView("history")}>Bestellhistorie ({orders.filter((order) => order.status === "delivered").length})</button></div><section className="inventory-panel admin-orders-panel"><div className="panel-heading"><div><h2>{view === "open" ? "Offene Bestellungen" : "Erledigte Bestellungen"}</h2><p>{view === "open" ? "Nach Lieferung als erledigt markieren." : "Alle abgeschlossenen Bestellungen bleiben archiviert."}</p></div><span className="snapshot-badge">Live verbunden</span></div>{visibleOrders.length === 0 ? <p className="empty-cart">Keine {view === "open" ? "offenen" : "erledigten"} Bestellungen vorhanden.</p> : <div className="admin-order-list">{visibleOrders.map((order) => { const location = one(order.location)?.name ?? "Unbekannter Betrieb"; const creator = one(order.creator)?.email ?? "Unbekannter Besteller"; return <article className="admin-order-card" key={order.id}><div className="admin-order-head"><div><strong>{location}</strong><small>{creator} · {new Date(order.created_at).toLocaleString("de-CH", { dateStyle: "medium", timeStyle: "short" })}</small></div><span className={`order-status ${order.status}`}>{order.status === "delivered" ? "Erledigt" : "Offen"}</span></div><div className="admin-order-items">{order.order_items.map((item, index) => <span key={`${item.wine?.[0]?.name}-${index}`}>{item.wine?.[0]?.name ?? "Wein"} <b>{item.cartons} Kartons</b></span>)}</div>{view === "open" && <button className="primary-button complete-order" onClick={() => completeOrder(order.id)}>✓ Lieferung erhalten · als erledigt markieren</button>}</article>; })}</div>}</section></div></main>;
}
